FROM node:16

COPY . .
WORKDIR /app
RUN npm install

ARG SERVER_PORT=3000
ARG NPM_SCRIPT=start:dev

ENV SERVER_PORT=$SERVER_PORT
ENV NPM_SCRIPT=$NPM_SCRIPT 

EXPOSE $SERVER_PORT
CMD [ "npm", "run", $NPM_SCRIPT ]